<?php

/**
 * Implementation of hook_form_alter().
 */
function special_menu_item_class_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'menu_edit_item') {
    $form['options']['special_menu_item_class'] = array(
      '#type' => 'textfield',
      '#title' => t('CSS class for this menu item'),
      '#description' => t('It\'s very useful when you want to build differnce menu item. Please sperate each class with space.'),
      '#size' => '30',
      '#default_value' => isset($form['menu']['options']['#value']['attributes']['class']) ? $form['menu']['options']['#value']['attributes']['class'] : '',
    );
    $form['#validate'][] = 'special_menu_item_class_validate';
  }
}

/**
 * Submit hanlder for add special class
 */
function special_menu_item_class_validate(&$form, &$form_state) {
  $item = &$form_state['values']['menu'];
  $item['options']['attributes']['class'] = $form_state['values']['special_menu_item_class'];
}